/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuporteRouteImport } from './routes/suporte'
import { Route as BoosterRouteImport } from './routes/booster'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicCsLiveRouteImport } from './routes/api.public.cs-live'

const SuporteRoute = SuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => rootRouteImport,
} as any)
const BoosterRoute = BoosterRouteImport.update({
  id: '/booster',
  path: '/booster',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCsLiveRoute = ApiPublicCsLiveRouteImport.update({
  id: '/api/public/cs-live',
  path: '/api/public/cs-live',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/booster': typeof BoosterRoute
  '/suporte': typeof SuporteRoute
  '/api/public/cs-live': typeof ApiPublicCsLiveRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/booster': typeof BoosterRoute
  '/suporte': typeof SuporteRoute
  '/api/public/cs-live': typeof ApiPublicCsLiveRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/booster': typeof BoosterRoute
  '/suporte': typeof SuporteRoute
  '/api/public/cs-live': typeof ApiPublicCsLiveRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/booster' | '/suporte' | '/api/public/cs-live'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/booster' | '/suporte' | '/api/public/cs-live'
  id: '__root__' | '/' | '/booster' | '/suporte' | '/api/public/cs-live'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BoosterRoute: typeof BoosterRoute
  SuporteRoute: typeof SuporteRoute
  ApiPublicCsLiveRoute: typeof ApiPublicCsLiveRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/suporte': {
      id: '/suporte'
      path: '/suporte'
      fullPath: '/suporte'
      preLoaderRoute: typeof SuporteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booster': {
      id: '/booster'
      path: '/booster'
      fullPath: '/booster'
      preLoaderRoute: typeof BoosterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cs-live': {
      id: '/api/public/cs-live'
      path: '/api/public/cs-live'
      fullPath: '/api/public/cs-live'
      preLoaderRoute: typeof ApiPublicCsLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoosterRoute: BoosterRoute,
  SuporteRoute: SuporteRoute,
  ApiPublicCsLiveRoute: ApiPublicCsLiveRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
